---
name: output-monad
version: 0.1.0.6
extra-source-files: [ ]
build-tools: [ ]
ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Widentities
  - -Wredundant-constraints
  - -Werror
  - -Wwarn=incomplete-uni-patterns
  - -Wwarn=orphans
dependencies:
  - base
  - containers
  - extra
  - mtl
  - pretty
  - text
  - transformers
  - utility-ht
  - exceptions
  - wl-pprint-text
library:
  source-dirs: src
  exposed-modules:
    - Control.Functor.Trans
    - Control.Monad.Output
    - Control.Monad.Output.Debug
    - Control.Monad.Output.Generic
    - Control.Monad.Output.Generic.Type
    - Control.Monad.Output.Type
tests:
  output-monad-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - output-monad
      - generic-random
      - hspec
      - QuickCheck >= 2.14
